[package]
name = "simple_accumulator"
version = "0.5.0"
edition = "2021"
authors = ["sn99 <siddharthn.099@gmail.com>, purnatag <purnatag@gmail.com>"]
description = "A simple accumulator"
repository = "https://github.com/sn99/SimpleAccumulator"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/sn99/SimpleAccumulator"
keywords = ["accumulator", "stats"]
documentation = "https://docs.rs/simple_accumulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
rand = "0.8.5"

[dependencies.float_eq]
version = "1"
features = ["derive"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[dev-dependencies]
ordered-float = "3.7.0"
plotly = {version = "0.8.3"}

[lib]
name = "simple_accumulator"

[[example]]
name = "error_mean"
